### PR TITLE
[WIP] Explicit formats in generated scala code.

### PR DESCRIPTION
**Pull request by adamdecaf**

### CODE REVIEW

**Comment by zmccoy** [comment]
:+1:

**Comment by zmccoy** [comment]
Did we give up on trying to get this to work since we found a work around on Jenkins?

**Comment by adamdecaf** [comment]
@zmccoy yea probably.

**Comment by trentio** [comment]
@adamdecaf good to close this then?

**Comment by adamdecaf** [comment]
@trentio yea

**Pull request closed without merging**
